#!/bin/bash

#INFO: tested, works

case "$1" in
help | h | "")
	echo "DOWNLOAD_FOLDER: $DOWNLOAD_FOLDER"
	echo "INSTALL_FOLDER: $INSTALL_FOLDER"
	echo "GITHUB_URL: $GITHUB_URL"
	echo "GITHUB_RELEASE_SUBURL: $GITHUB_RELEASE_SUBURL"
	echo "GITHUB_RELEASE_DOWNLOAD_SUBURL: $GITHUB_RELEASE_DOWNLOAD_SUBURL"
	echo "VERSION_GREP_PATTERN: $VERSION_GREP_PATTERN"
	echo "VERSION_SED_PATTERN: $VERSION_SED_PATTERN"
	echo "VERSION_PREFIX: $VERSION_PREFIX"
	echo "VERSION_SUFFIX: $VERSION_SUFFIX"
	echo "EXEC_NAME: $EXEC_NAME"
	echo "EXEC_PKG_NAME_PATTERN: $EXEC_PKG_NAME_PATTERN"
	echo "EXEC_RAW_NO_NEED_TO_UNZIP: $EXEC_RAW_NO_NEED_TO_UNZIP"
	echo "UNZIP_CMD_PREFIX: $UNZIP_CMD_PREFIX"
	exit 1
	;;
*) ;;
esac

DOWNLOAD_FOLDER=$1
INSTALL_FOLDER=$2
GITHUB_URL=$3
GITHUB_RELEASE_SUBURL=$4
GITHUB_RELEASE_DOWNLOAD_SUBURL=$5
VERSION_GREP_PATTERN=$6
VERSION_SED_PATTERN=$7
VERSION_PREFIX=$8
VERSION_SUFFIX=$9
EXEC_NAME=${10}
EXEC_PKG_NAME_PATTERN=${11} # using ### to represent version
EXEC_RAW_NO_NEED_TO_UNZIP=${12}
UNZIP_CMD_PREFIX=${13}

echo "DOWNLOAD_FOLDER: $DOWNLOAD_FOLDER"
echo "INSTALL_FOLDER: $INSTALL_FOLDER"
echo "GITHUB_URL: $GITHUB_URL"
echo "GITHUB_RELEASE_SUBURL: $GITHUB_RELEASE_SUBURL"
echo "GITHUB_RELEASE_DOWNLOAD_SUBURL: $GITHUB_RELEASE_DOWNLOAD_SUBURL"
echo "VERSION_GREP_PATTERN: $VERSION_GREP_PATTERN"
echo "VERSION_SED_PATTERN: $VERSION_SED_PATTERN"
echo "VERSION_PREFIX: $VERSION_PREFIX"
echo "VERSION_SUFFIX: $VERSION_SUFFIX"
echo "EXEC_NAME: $EXEC_NAME"
echo "EXEC_PKG_NAME_PATTERN: $EXEC_PKG_NAME_PATTERN"

echo "Querying $GITHUB_URL/$GITHUB_RELEASE_SUBURL"
VERSION_LATEST=$(
	curl -L $GITHUB_URL/$GITHUB_RELEASE_SUBURL |
		grep -oE "$VERSION_GREP_PATTERN" |
		sort -r --version-sort |
		uniq |
		sed "$VERSION_SED_PATTERN" |
		awk 'NR==1{print $1}'
)
echo "Found $EXEC_NAME latest veriosn: $VERSION_LATEST"

EXEC_PKG_FILE_NAME=$(
	echo "$EXEC_PKG_NAME_PATTERN" | sed "s/###/$VERSION_LATEST/"
)

echo "EXEC_PKG_FILE_NAME: $EXEC_PKG_FILE_NAME"
echo "DOWNLOAD_FOLDER: $DOWNLOAD_FOLDER"

mkdir -p $DOWNLOAD_FOLDER && cd $DOWNLOAD_FOLDER

if [[ ! -f $EXEC_PKG_FILE_NAME ]]; then
	wget "$GITHUB_URL/$GITHUB_RELEASE_DOWNLOAD_SUBURL/$VERSION_PREFIX$VERSION_LATEST$VERSION_SUFFIX/$EXEC_PKG_FILE_NAME"
	[[ ! $? -eq 0 ]] && exit 1
else
	echo "$EXEC_PKG_FILE_NAME already exits."
	echo "Use cached version."
fi

if [[ "zip" -eq "${12}" ]]; then
	$UNZIP_CMD_PREFIX $EXEC_PKG_FILE_NAME
fi
EXEC_PATH=$(find . -name $EXEC_NAME)
echo "EXEC_PATH: $EXEC_PATH"
chmod +x $EXEC_PATH
cp -f $EXEC_PATH $INSTALL_FOLDER/$EXEC_NAME
echo "$EXEC_NAME installed."
